#!/usr/bin/env node
/**
 * scripts/prep-logo.js
 *
 * Processes C:\Users\genes\Downloads\Upthrust_Logo.png into two
 * base64-encoded, transparency-trimmed PNGs and writes them as
 * TypeScript string exports to lib/upthrust-logo-base64.ts.
 *
 * Run once:  node scripts/prep-logo.js
 */

const sharp = require('sharp');
const path = require('path');
const fs = require('fs');

const SOURCE = 'C:\\Users\\genes\\Downloads\\Upthrust Logo.png';
const OUT_TS = path.join(__dirname, '..', 'lib', 'upthrust-logo-base64.ts');

// Near-white threshold: any pixel with R, G, B all > 235 becomes transparent.
const WHITE_THRESHOLD = 235;

async function makeTransparent(inputBuffer) {
  const { data, info } = await sharp(inputBuffer)
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });

  const { width, height, channels } = info; // channels === 4 (RGBA)
  const pixels = new Uint8Array(data);

  for (let i = 0; i < pixels.length; i += 4) {
    const r = pixels[i];
    const g = pixels[i + 1];
    const b = pixels[i + 2];
    if (r > WHITE_THRESHOLD && g > WHITE_THRESHOLD && b > WHITE_THRESHOLD) {
      pixels[i + 3] = 0; // alpha → transparent
    }
  }

  return sharp(Buffer.from(pixels), {
    raw: { width, height, channels },
  }).png().toBuffer();
}

async function main() {
  if (!fs.existsSync(SOURCE)) {
    console.error(`ERROR: source file not found:\n  ${SOURCE}`);
    console.error('Place the logo PNG at that path and re-run.');
    process.exit(1);
  }

  console.log('Reading source:', SOURCE);
  const raw = fs.readFileSync(SOURCE);

  // ── Step 1: make background transparent ──────────────────────────────────
  console.log('Removing near-white background…');
  const transparent = await makeTransparent(raw);

  // ── Step 2: trim empty space ──────────────────────────────────────────────
  console.log('Trimming…');
  const trimmed = await sharp(transparent).trim({ threshold: 2 }).png().toBuffer();

  // ── Step 3: produce header version (600px wide) ───────────────────────────
  console.log('Resizing → header (600px wide)…');
  const headerBuf = await sharp(trimmed)
    .resize({ width: 600, withoutEnlargement: false })
    .png({ compressionLevel: 9, effort: 10 })
    .toBuffer();

  // ── Step 4: produce watermark version (1000px wide) ───────────────────────
  console.log('Resizing → watermark (1000px wide)…');
  const watermarkBuf = await sharp(trimmed)
    .resize({ width: 1000, withoutEnlargement: false })
    .png({ compressionLevel: 9, effort: 10 })
    .toBuffer();

  // ── Step 5: base64 encode ─────────────────────────────────────────────────
  const headerB64    = `data:image/png;base64,${headerBuf.toString('base64')}`;
  const watermarkB64 = `data:image/png;base64,${watermarkBuf.toString('base64')}`;

  console.log(`Header data URL length:    ${headerB64.length.toLocaleString()} chars`);
  console.log(`Watermark data URL length: ${watermarkB64.length.toLocaleString()} chars`);

  // ── Step 6: write TypeScript exports ─────────────────────────────────────
  const ts = [
    '// AUTO-GENERATED by scripts/prep-logo.js — do not edit by hand.',
    '// Re-run the script to regenerate from a new source PNG.',
    '',
    `export const UPTHRUST_LOGO_DATA_URL = "${headerB64}";`,
    '',
    `export const UPTHRUST_WATERMARK_DATA_URL = "${watermarkB64}";`,
    '',
  ].join('\n');

  fs.writeFileSync(OUT_TS, ts, 'utf8');

  const outSize = fs.statSync(OUT_TS).size;
  console.log(`\nWrote: ${OUT_TS}`);
  console.log(`  File size: ${(outSize / 1024).toFixed(1)} KB`);
  console.log('  UPTHRUST_LOGO_DATA_URL      ✓');
  console.log('  UPTHRUST_WATERMARK_DATA_URL ✓');
  console.log('\nDone.');
}

main().catch(err => {
  console.error('Script failed:', err.message);
  process.exit(1);
});
